[2023-10-17T16:37:10.346+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: games_details.create_details_dataset scheduled__2023-10-16T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'upload_csv_to_gcs'}
[2023-10-17T16:37:10.348+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-10-17T16:38:02.572+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: games_details.create_details_dataset scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-17T16:38:02.579+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: games_details.create_details_dataset scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-17T16:38:02.579+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 3
[2023-10-17T16:38:02.588+0000] {taskinstance.py:1380} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_details_dataset> on 2023-10-16 00:00:00+00:00
[2023-10-17T16:38:02.593+0000] {standard_task_runner.py:57} INFO - Started process 2267 to run task
[2023-10-17T16:38:02.596+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'games_details', 'create_details_dataset', 'scheduled__2023-10-16T00:00:00+00:00', '--job-id', '485', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp69i5awng']
[2023-10-17T16:38:02.598+0000] {standard_task_runner.py:85} INFO - Job 485: Subtask create_details_dataset
[2023-10-17T16:38:02.631+0000] {task_command.py:415} INFO - Running <TaskInstance: games_details.create_details_dataset scheduled__2023-10-16T00:00:00+00:00 [running]> on host ee1b836360c8
[2023-10-17T16:38:02.687+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='games_details' AIRFLOW_CTX_TASK_ID='create_details_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-16T00:00:00+00:00'
[2023-10-17T16:38:02.694+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T16:38:02.697+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T16:38:02.731+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value games.
[2023-10-17T16:38:02.731+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value pristine-flames-400818.
[2023-10-17T16:38:02.731+0000] {bigquery.py:481} INFO - Creating dataset: games in project: pristine-flames-400818 
[2023-10-17T16:38:03.365+0000] {bigquery.py:2030} INFO - Dataset games already exists.
[2023-10-17T16:38:03.429+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=games_details, task_id=create_details_dataset, execution_date=20231016T000000, start_date=20231017T163802, end_date=20231017T163803
[2023-10-17T16:38:03.490+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-17T16:38:03.519+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
